Repository GDSC-KNU/3rd-toyproject-frontend-2, pull requests merged in 2024-01, with the labels that each got.

#2 [style] 국물류, 안주류 페이지 스타일 완성
  README.md
  package-lock.json
  package.json
  src/assets/alltang.png
  src/assets/bazirak.png
  src/assets/dakbal.png
  src/assets/fishcake.png
  src/assets/ggozi.png
  src/assets/gobdori.png
  src/assets/kongbul.png
  src/assets/muktae.png
  src/assets/sundubu.png
  src/assets/topoki.png
  src/assets/zzambbong.png
  src/assets/zzuggumi.png
  src/components/Card/MenuCard.js
  src/pages/BackgroundColor.css
  src/pages/SnackPage.js
  src/pages/SoupPage.js
Labels: style

#5 [Feat] 카테고리바 페이지별 컬러 변경 기능 추가
  package-lock.json
  src/components/Button/CategoryButton.js
  src/components/Card/MenuCard.js
  src/components/CategoryBar.js
  src/pages/CallPage.js
  src/pages/DrinkPage.js
  src/pages/SnackPage.js
  src/pages/SoupPage.js
Labels: feat, style

#6 [Fix]: 크기 안맞는 부분 수정
  src/pages/SnackPage.js
Labels: style

#9 CallPage 및 여러가지 수정
  package-lock.json
  package.json
  src/assets/Group.png
  src/components/Button/CallButton/AllRemove.js
  src/components/Button/CallButton/Minus.js
  src/components/Button/CallButton/Plus.js
  src/components/Button/CallButton/StaffCallButton.js
  src/components/Button/FooterButton.js
  src/components/Card/CallCard.js
  src/components/CardContainer.js
  src/components/OrderContainer.js
  src/pages/BillPage.js
  src/pages/CallPage.js
  src/styles/BillPageStyle.js
  src/styles/CallPageStyle.js
Labels: feat, style

#10 [Fix]: 오류발생하는 부분 수정
  src/components/Card/MenuCard.js
  src/pages/BillPage.js
Labels: bug, style

#13 [Feat] 주문페이지 주문 추가 기능 구현
  src/components/Card/MenuCard.js
  src/pages/DrinkPage.js
  src/pages/SnackPage.js
  src/pages/SoupPage.js
Labels: ✨ feat

#15 [Feat] 주문 정보 쿠키 설정
  src/components/Card/MenuCard.js
Labels: ✨ feat

#16 [chore]: 주문페이지 주문내역 누적안됨 오류 수정
  package.json
  src/components/Card/MenuCard.js
Labels: 😡 bug fix

#14 Feat/call page
  src/components/Button/CallButton/AllRemove.js
  src/components/Button/CallButton/Minus.js
  src/components/Button/CallButton/Plus.js
  src/components/Button/CallButton/RequestButton.js
  src/components/Button/CallButton/StaffCallButton.js
  src/components/ButtonContainer.js
  src/components/Card/CallCard.js
  src/components/CardContainer.js
  src/components/OrderContainer.js
  src/pages/CallPage.js
  src/store/callAction.js
  src/store/callSlice.js
  src/store/store.js
  src/styles/CallPageStyle.js
Labels: ✨ feat, 🙌🏻 help, 🎨 style

#18 Feature/cart page
  src/components/Button/DeleteAllButton.js
  src/components/Button/OrderButton.js
  src/components/Button/PaymentButton.js
  src/components/Card/MenuCard.js
  src/components/List/CartList.js
  src/pages/CartPage.js
  src/styles/CartPageStyle.js
Labels: ✨ feat
